# Generated by Django 3.1 on 2023-03-16 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='handle',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='personal',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='meta',
            field=models.TextField(default='None', max_length=160),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta',
            field=models.TextField(default='None', max_length=160),
        ),
    ]
