# Generated by Django 3.1 on 2023-03-18 01:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overview',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_alt',
            field=models.TextField(default='A picture'),
        ),
    ]
