# Generated by Django 3.1 on 2023-03-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20230320_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta',
            field=models.TextField(default='None', max_length=200),
        ),
    ]
