# Generated by Django 3.1 on 2023-03-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Signup',
        ),
    ]
